### ISSUE TITLE
Anonymity and Handles

### ISSUE THREAD

**Issue by bnb** [layervault/news-guidelines#1]
Hey there. I'm a [long time user](https://news.layervault.com/u/781/bitand-bang) and supporter of DN. I really love the site, as I feel like I'm able to connect with the types of designers I want to. 

I use a handle on the Internet for all my design and development accounts. All of them. I know it's probably unimaginable, but I want to separate my real life and my work life. I don't completely separate the two--in just a couple places you'll find my real name attached to my handle. 

However, I don't want DN to be one of those places. It's nothing against the DN community, the web, or whoever. I would simply like to be known as I have presented myself. I don't think this should be against the rules. Obviously I, a user using a handle, have contributed _something_ to the community, and I'd like to think that it is positive. I ask you to reconsider the anonymity/handle rule, in order to allow people like myself to participate without breaking the rules.

**Comment by danielgolden** [comment]
In cases where your reputation and and success of your business is tied to your handle, it makes sense to allow this form of identification. But to be fair to DN, how can you regulate this?

**Comment by bnb** [comment]
@danielgolden The answer is you don't. There's not really a need to regulate people using handles. It's an intrinsic part of the Internet. It's not something to dismiss or force on people.

**Comment by kellysutton** [comment]
While we understand the need for anonymity online, Designer News is not a place where we see a strong need for it. We encourage members to use their real names to remind everyone that humans use the site, not users. The best way we have found out to do that is to require real names and job titles. 

We won't be changing that requirement any time soon.
