### ISSUE TITLE
Issues needs to be activated on new repo

### ISSUE THREAD

**Issue by techpeace** [layervault/news-guidelines#2]
The [new repo linked to from the website](https://github.com/DesignerNews/news-guidelines) seems to have the issues tab disabled.

Also, would y'all consider adding a license to this repo? I'm investigating setting up a similar community, and I was wondering if I could use these (excellent) guidelines as a basis for developing a set for that site.

Thanks!

**Comment by jodyheavener** [comment]
Hi there!

Sorry for the delay. We've enabled Issues for the DN fork of this repo.

Unfortunately for the time being we're not in a position to officially license the Guidelines on Designer News. Feel free to draw inspiration from them, though -- we won't be mad!
